# Generated by Django 5.0.6 on 2026-02-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10)),
                ('exercise_minutes_per_week', models.IntegerField(default=0)),
                ('smoking_status', models.CharField(choices=[('none', 'None'), ('occasional', 'Occasional'), ('daily', 'Daily')], default='none', max_length=20)),
                ('weight_kg', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('diet_quality', models.CharField(choices=[('healthy', 'Healthy'), ('moderate', 'Moderate'), ('unhealthy', 'Unhealthy')], default='moderate', max_length=20)),
                ('alcohol_consumption', models.CharField(choices=[('none', 'None'), ('light', 'Light'), ('heavy', 'Heavy')], default='none', max_length=20)),
                ('has_health_issues', models.BooleanField(default=False)),
                ('estimated_lifespan_years', models.FloatField()),
                ('base_age', models.FloatField(default=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unique_id', models.CharField(db_index=True, max_length=32, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
